language: c

sudo: false

cache:
  directories:
    - ~/.cabal/packages
    - ~/.cabal/store

matrix:
  include:
    - env: CABALVER=2.4 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.4.4
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.5], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - ghc --version
  - travis_retry cabal update

script:
  - cabal new-build parser-combinators parser-combinators-tests --enable-tests --enable-benchmarks --flags=dev
  - cabal new-test parser-combinators-tests
  - cabal new-haddock parser-combinators
  # - cabal new-haddock parser-combinators-tests
  - cabal sdist
  - cd parser-combinators-tests && cabal sdist

notifications:
  email: false
