language: c

sudo: false

cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    - env: CABALVER=1.24 GHCVER=7.4.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.4.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=7.6.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.6.3], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.2.2], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - case "$GHCVER" in
     "7.4.2") cabal configure -v2 -f dev ;;
     "7.6.3") cabal configure -v2 -f dev ;;
     *) cabal configure --enable-tests --enable-coverage -v2 -f dev ;;
   esac
 - cabal build
 - cabal test --show-details=always --test-option=--qc-max-success=1000
 - cabal sdist
 - case "$GHCVER" in
     "7.4.2") true ;;
     "7.6.3") true ;;
     *) cabal haddock | grep "100%" | wc -l | grep "5" ;;
   esac

notifications:
  email: false
